apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: productcatalogservice
  description: Auto-updated catalog file for productcatalogservice
spec:
  type: service
  lifecycle: production
  owner: team-a
