apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: currencyservice
  description: Auto-updated catalog file for currencyservice
spec:
  type: service
  lifecycle: production
  owner: team-a
