apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emailservice
  description: Auto-updated catalog file for emailservice
spec:
  type: service
  lifecycle: production
  owner: team-a
