apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shippingservice
  description: Auto-updated catalog file for shippingservice
spec:
  type: service
  lifecycle: production
  owner: team-a
