apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkoutservice
  description: Auto-updated catalog file for checkoutservice
spec:
  type: service
  lifecycle: production
  owner: team-a
