apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paymentservice
  description: Auto-updated catalog file for paymentservice
spec:
  type: service
  lifecycle: production
  owner: team-a
