apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example1
  description: A service named example1 in the current project.
  tags:
    - python
    - sql
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
  business_unit: Group1
  organization: Group1
  cluster: cluster1
  env: dev1
  region: eus1
  wildcard_ingress_dns: .example1.com
spec:
  type: service
  owner: user:guest
  system: ecommerce-system
  lifecycle: experimental
  dependsOn: ['component:example2']
  apiConsumedBy: ['component:example3']
