apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendationservice
  description: Auto-updated catalog file for recommendationservice
spec:
  type: service
  lifecycle: production
  owner: team-a
