apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loadgenerator
  description: Auto-updated catalog file for loadgenerator
spec:
  type: service
  lifecycle: production
  owner: team-a
